Profile model
Abhi-S-1/fun-kickoff-project pull request #3
Opened 2022-01-09 01:10 UTC by Abhi-S-1

### What this PR does (required):
- Created Model for Profile 

### Screenshots / Videos (front-end only):

### Any information needed to test this feature (required):
- View profile model 

### Any issues with the current functionality (optional):

2022-01-10 14:03 UTC, moffatethan requested changes
Just some changes regarding code style. Rest looks fine to me!

2022-01-10 14:03 UTC, moffatethan commented on server/models/Availability.js
> +  week_of: {
`weekOf` let's preference camelCase please as it's JavaScript convention.

2022-01-10 14:03 UTC, moffatethan commented on server/models/Availability.js
> +  monday: {
Not quite the approach for availability I want to take but we'll work more on it this week.

2022-01-10 14:03 UTC, moffatethan commented on server/models/Profile.js
> +  first_name: {
```suggestion
  firstName: {
```

Ditto throughout the schema 🚀

2022-01-10 14:03 UTC, moffatethan commented on server/models/Profile.js
> +  },
Nice 👍🏻

2022-01-10 16:30 UTC, Abhi-S-1 commented
Thanks for the comments. Changes Made 👍🏻

2022-01-11 04:40 UTC, moffatethan approved these changes

2022-01-11 04:46 UTC, merged